### ISSUE TITLE
 Unhandled Exception: Unsupported operation: Infinity or NaN toInt

### ISSUE THREAD

**Issue by klaszlo8207** [peng8350/flutter_gifimage#3]
Tried with this:

https://www.howtogeek.com/wp-content/uploads/2019/09/2.gif (I downloaded to my sd card..)

    return Align(
        child: GifImage(
          image: FileImage(File(path)),
          controller: _gifController,
          onFetchCompleted: () {
            _gifController.repeat(period: Duration(milliseconds: 300));
          },
        ),
        alignment: Alignment.center);

got an exception:

 Unhandled Exception: Unsupported operation: Infinity or NaN toInt
E/flutter ( 4817): #0      double.toInt (dart:core-patch/double.dart:194:36)
E/flutter ( 4817): #1      GifImageState.didChangeDependencies.<anonymous closure>.<anonymous closure> (package:flutter_gifimage/flutter_gifimage.dart:163:49)
E/flutter ( 4817): #2      State.setState (package:flutter/src/widgets/framework.dart:1148:30)
E/flutter ( 4817): #3      GifImageState.didChangeDependencies.<anonymous closure> (package:flutter_gifimage/flutter_gifimage.dart:160:11)
E/flutter ( 4817): #4      _rootRunUnary (dart:async/zone.dart:1134:38)
E/flutter ( 4817): #5      _CustomZone.runUnary (dart:async/zone.dart:1031:19)
E/flutter ( 4817): #6      _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
E/flutter ( 4817): #7      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
E/flutter ( 4817): #8      Future._propagateToListeners (dart:async/future_impl.dart:709:32)
E/flutter ( 4817): #9      Future._completeWithValue (dart:async/future_impl.dart:524:5)
E/flutter ( 4817): #10     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:554:7)
E/flutter ( 4817): #11     _rootRun (dart:async/zone.dart:1126:13)

**Comment by gisinator** [comment]
try setting min and max parameters in .repeat() method. Unfortunately I could not make "lowerbound" and "upperbound" work here, but it did work with values like 1 for min and 10 for max for example. Still trying to figure out how to automatically set the last frame index as max value...

**Comment by gisinator** [comment]
Found a workaround: In order to repeat the gif from first to last frame, make use of fetchGif() method before calling .repeat() method. fetchGif returns a List<ImageInfo> and its .length equals the number of frames. Use this number for max and you're good to go...

**Comment by klaszlo8207** [comment]
I just not added the bounds, so that was the mistake. Closing now.

**Comment by ThinkDigitalSoftware** [comment]
> I just not added the bounds, so that was the mistake. Closing now.

It still needs a proper error message though
